name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "LMSPumpIt.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
